name: pie_menu
description: A Flutter package providing a highly customizable circular/radial context menu
version: 3.2.1
homepage: https://github.com/rasitayaz/flutter-pie-menu
repository: https://github.com/rasitayaz/flutter-pie-menu
issue_tracker: https://github.com/rasitayaz/flutter-pie-menu/issues

funding:
  - https://buymeacoffee.com/rasitayaz

screenshots:
  - description: Pie Menu Example
    path: pie.jpg

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: null
